export type EventColumnId = 
  | 'event_id'
  | 'event_name'
  | 'fullname'
  | 'email'
  | 'phone'
  | 'event_time'
  | 'event_type'
  | 'event_source'
  | 'user_id'
  | 'session_id'
  | 'pageview_id'
  | 'profession_id'
  | 'product_id'
  | 'funnel_id' 